# Generated by Django 3.2.9 on 2021-11-20 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='craet_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 19, 18, 34, 438912, tzinfo=utc)),
        ),
    ]
