# Generated by Django 3.2.9 on 2021-11-20 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211120_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='craet_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 19, 19, 8, 265423, tzinfo=utc)),
        ),
    ]
